CREATE TABLE users (
	`_id` INT NOT NULL AUTO_INCREMENT,
	`_identifier` CHAR(36) NOT NULL COMMENT 'Public identifier',
	`username` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`password` VARCHAR(255) NOT NULL COMMENT 'Stored using BCRYPT',
	`_status` ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
	`_crc_identifier` INT UNSIGNED NOT NULL COMMENT 'CRC32 generated by MySQL function',
	`_crc_username` INT UNSIGNED NOT NULL COMMENT 'CRC32 generated by MySQL function',
	`_crc_email` INT UNSIGNED NOT NULL COMMENT 'CRC32 generated by MySQL function',
	`_created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`_updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`_id`),
	INDEX `users_idx_status` (`_status`),
	INDEX `users_idx_crc_identifier` (`_crc_identifier`),
	INDEX `users_idx_crc_username` (`_crc_username`),
	INDEX `users_idx_crc_email` (`_crc_email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;